global:
  scrape_interval:     10s
  evaluation_interval: 10s
rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
         - targets: ['localhost:9090']
