{
 "title": "Mikrotik Exporter",
 "description": "Mikrotik RouterOS metrics",
 "tags": [
  "dashboard",
  "mikrotik"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(mikrotik_system_uptime,address)"
   }
  ]
 },
 "panels": [
  {
   "title": "System uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mikrotik_system_uptime{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mikrotik_system_cpu_load{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memória disponivel",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (mikrotik_system_free_memory{address=\"$node\"} / (mikrotik_system_total_memory{address=\"$node\"})))* 100",
     "legendFormat": "Memória disponivel {{job}}"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mikrotik_system_total_hdd_space{address=\"$node\"} - mikrotik_system_free_hdd_space{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Uso Memória",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mikrotik_system_total_hdd_space{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total Memória",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mikrotik_interface_rx_byte{address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mikrotik_interface_tx_byte{address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out - {{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mikrotik_interface_rx_error{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "InErrors {{interface}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mikrotik_interface_tx_error{address=\"$node\"}",
     "legendFormat": "Out Errors {{interface}}"
    }
   ]
  }
 ]
}