{
 "title": "System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU - 10.240.0.4",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"10.240.0.4:9100\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU - 10.240.0.5",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"10.240.0.5:9100\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU - 10.240.0.6",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"10.240.0.6:9100\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uso de CPU dos hosts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"10.240.0.4:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "10.240.0.4"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"10.240.0.5:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "10.240.0.5"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"10.240.0.6:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "10.240.0.6"
    }
   ]
  },
  {
   "title": "Uso de memória por node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes-(node_memory_MemTotal_bytes-node_memory_MemFree_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total de Node exporter linux",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_context_switches_total)"
    }
   ]
  },
  {
   "title": "Espaço em uso",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1-(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total de container",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Uso de CPU por contêiner",
   "type": "gauge",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=\"aks-agentpool-16351447-vmss000000\",image!=\"\"}[5m]) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=\"aks-agentpool-16351447-vmss000001\",image!=\"\"}[5m]) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=\"aks-agentpool-16351447-vmss000003\",image!=\"\"}[5m]) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Uso de memória por contêiner",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"aks-agentpool-16351447-vmss000000\",image!=\"\"}",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"aks-agentpool-16351447-vmss000001\",image!=\"\"}",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"aks-agentpool-16351447-vmss000002\",image!=\"\"}",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Tráfego de rede",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"10.240.0.4:9100\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{device}} - Download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.0.7:9100\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{device}} - Upload"
    }
   ]
  },
  {
   "title": "Tráfego de rede",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"10.240.0.5:9100\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{device}} - Download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.0.7:9100\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{device}} - Upload"
    }
   ]
  },
  {
   "title": "Tráfego de rede",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"10.240.0.6:9100\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{device}} - Download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.0.7:9100\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{device}} - Upload"
    }
   ]
  }
 ]
}