{
 "title": "Zabbix",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Linux Server", "type": "stat", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 } },
  { "title": "Mikrotik", "type": "stat", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Uso de CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "bull" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memória RAM",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "bull" },
     "item": { "filter": "Total memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "bull" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Espaço em disco em uso",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "application": { "filter": "Filesystem /" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "bull" },
     "item": { "filter": "/: Space utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": {
      "filter": "Free disk space on / (percentage)"
     },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Processos em Execução",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Interface enp0s31f6" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "bull" },
     "item": {
      "filter": "Interface enp0s31f6: Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface enp0s31f6" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "bull" },
     "item": { "filter": "Interface enp0s31f6: Bits sent" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}