global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'monitoring'
rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'exporter_linux-01'
    metrics_path: '/metrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 1s
    static_configs:
         - targets: ['192.168.0.7:9111']

  - job_name: 'exporter_ping-01'
    metrics_path: '/metrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 1s
    static_configs:
         - targets: ['192.168.0.7:9121']


  - job_name: 'exporter_mikritik-01'
    metrics_path: '/metrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 1s
    static_configs:
         - targets: ['192.168.0.7:9436']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080